vsphere_server = "10.0.2.253"
vsphere_user = "8888"
vsphere_password = "8888"
datacenter         = "Datacenter"
datastore          = "NTNXStorage"
cluster            = "test"
network_name       = "Backplane Network"
template_name        = "centos7.9模板"
