vsphere_server = "10.0.2.253"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "!QAZ2wsx#EDC"
datacenter         = "Datacenter"
datastore          = "NTNXStorage"
network_name       = "Backplane Network"
template_name        = "centos7.9模板"
vsphere_host = "10.0.2.8"